---
  openapi: "3.0.0"
  info: 
    title: "no_title"
    description: "no_description"
    version: "no_version"
  servers: 
    - 
      url: "http://localhost:3000"
  tags: 
    - 
      name: "info"
      description: "Main info about API"
    - 
      name: "health"
      description: "Everything about API's health"
  paths: 
    /api/health: 
      get: 
        tags: 
          - "health"
        summary: "Returns the health status of the API"
        responses: 
          200: 
            description: "OK"
            content: 
              application/json: 
                schema: 
                  type: "object"
                  properties: 
                    status: 
                      type: "string"
                      example: "DOWN"
    /api/info: 
      get: 
        tags: 
          - "info"
        summary: "Return the health status of the API"
        responses: 
          200: 
            description: "OK"
            content: 
              application/json: 
                schema: 
                  type: "object"
                  properties: 
                    version: 
                      type: "string"
                      example: "0.0.0"
                    author: 
                      type: "string"
                      example: "John Doe"
